version: '2'
services:
  db:
    container_name: db
    image: postgres:9.4.1
    ports:
      - "5555:5555"
  client:
    container_name: client
    build: ./client
    command: bash -c "npm install && ls && node server.js"
    ports:
      - "8080:8080"
    links:
      - web
    volumes:
      - ./client:/client

  web:
    container_name: web
    build: .
    command: rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/sample_app
