json.id task.id
json.name task.name
json.title task.title
json.description task.description
json.project_id task.project_id
json.user_id task.user_id
json.executor_id task.executor_id
json.time_do task.time_do
json.time_done task.time_done
json.status task.status
json.type task.type
json.priority task.priority
