export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';


export const FETCH_ALL_TASKS = 'FETCH_ALL_TASKS';
export const FETCH_ALL_TASKS_SUCCESS = 'FETCH_ALL_TASKS_SUCCESS';
export const FETCH_ALL_TASKS_FAILURE = 'FETCH_ALL_TASKS_FAILURE';


export const MOVE_TASK = 'MOVE_TASK';
export const MOVE_TASK_SUCCESS = 'MOVE_TASK_SUCCESS';
export const MOVE_TASK_FAILURE = 'MOVE_TASK_FAILURE';


