export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';




export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const UPDATE_PROJECTS_COMPLETE = 'UPDATE_PROJECTS_COMPLETE';


export const FETCH_MEMBERS_AND_ROLES = 'FETCH_MEMBERS_AND_ROLES';
export const FETCH_MEMBERS_AND_ROLES_SUCCESS = 'FETCH_MEMBERS_AND_ROLES_SUCCESS';
export const FETCH_MEMBERS_AND_ROLES_FAILURE = 'FETCH_MEMBERS_AND_ROLES_FAILURE';